---
title: "Cap 5 - Spending Our Data"
author: "Caio Sain Vallio"
format: 
    html:
      toc: true
      self-contained: true
      code-fold: show
---


```{r}
#| message: false
#| warning: false

data(ames, package = "modeldata")
dim(ames)

```


```{r}
#| label: fig-salse
#| fig-cap:  Sale prices of houses in Ames, Iowa.
#| message: false
#| warning: false

library(tidymodels)
tidymodels_prefer()
ggplot(ames, aes(x = Sale_Price)) +
  geom_histogram(bins = 50, col= "white")

```

```{r}
#| label: fig-salselog
#| fig-cap:  Sale prices of houses in Ames, Iowa after a log (base 10) transformation.
#| message: false
#| warning: false

ggplot(ames, aes(x = Sale_Price)) +
  geom_histogram(bins = 50, col= "white") +
  scale_x_log10()

```

# Common Methods for Splitting Data




```{r}
#| message: false
#| warning: false

library(tidymodels)
tidymodels_prefer()

# Set the random number stream using `set.seed()` so that the results can be reproduced later.
set.seed(501)

# Save the split information for an 80/20 split of the data
ames_split <- initial_split(ames, prop = 0.80)

ames_split

```


```{r}
#| message: false
#| warning: false

ames_train <- training(ames_split)
ames_test <- testing(ames_split)
dim(ames_train)

```


```{r}
#| message: false
#| warning: false

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)
dim(ames_train)

```

# What About a Validation Set?




```{r}
#| message: false
#| warning: false


```


```{r}
#| message: false
#| warning: false


```


```{r}
#| message: false
#| warning: false


```


```{r}
#| message: false
#| warning: false


```

